### ISSUE TITLE
No support for Attribute inheritance

### ISSUE THREAD

**Issue by rares-mollie** [Crell/AttributeUtils#1]
## Detailed description

While trying to use the library for managing attributes used within inheritance (a very useful feature I'd prefer not to implement myself) I discovered that the design choice of always returning an instance of the attribute makes it impossible to use inheritance for the attribute types themselves.

in my case I'm trying to build something that uses the following:

```
interface AttributeInterface {
    public function isEnabled(): bool;
}

#[\Attribute]
class MyMethod implements AttributeInterface {
    public function isEnabled(): bool
    {
      return true;
    }
}

class Something {
    #[MyMethod()]
    public function myMethod(): bool
    {
       return true;
    }
}
```

To handle this I'm currently using reflection with:

```
$reflectionClass->getAttributes(AttributeInterface::class, ReflectionAttribute::IS_INSTANCEOF);
```

But of course would prefer to use this library instead.

## Context

By using the attributes in this way I can create general handlers for certain kinds of attributes while allowing for custom implementations of the attributes.

## Possible implementation

A possible implementation would not return instances of the attribute class in the search but rather use `ReflectionAttribute::IS_INSTANCEOF` to do the search and then return instances of the found attributes instead, and an empty list if none are found.

## Your environment
not relevant

**Comment by Crell** [comment]
I'm not entirely sure I follow.  In the current form, `ClassAnalyzer` only works on, well, classes.  Your example doesn't include a class-level attribute so I don't know how you'd run the analysis.  Though, I suppose you could use `AttributeParser` directly.  That... could work?

Can you provide a full test of what you are trying to do and showing how it doesn't?  Preferably as a PR with the failing test.

**Comment by rares-mollie** [comment]
After further testing it appears that I was in fact holding it wrong, I managed to do what I intended

**Comment by Crell** [comment]
Good to hear.  That clears me to make a new release soon with a few new features added over the weekend. 😄
